### PR TITLE
Defaults shipping coutry to Finland if not present

### PR DESCRIPTION
**Pull request by joosev**
This should create fix for the pickup problem module has now. This is not tested, so don't merge before testing that it works. In theory, it should work.

### CODE REVIEW

**Comment by joosev** [comment]
Atleast now it goes trhough testing.. Can someone test, if this really really really really works?

**Comment by joosev** [comment]
Tested this version and it seems to work.

**Comment by joosev** [comment]
Accidently fucked up this branch thingie, and changed this pull request so it removes the old one.. ups. Anyway, previous pull request is also included in the pull request that solves #18 .

**Comment by joosev** [comment]
This will fix issue #24

**Comment by l3ku** [comment]
Thanks for the PR! Tested this, and the changes made indeed fix #24, but how does this solve #18? Also, is there a reason why in https://github.com/Seravo/woo-pakettikauppa/pull/19/commits/6eb6758dcbc91c9d887ffd2db91d4ad812987ff2#diff-155ffcecf3e49923b61cb4dbb259ab3fR283 you added lines that were later removed in https://github.com/Seravo/woo-pakettikauppa/pull/19/commits/bb38ba4ebef8110cd302b61da27b14d7cec1b985#diff-155ffcecf3e49923b61cb4dbb259ab3fL287?

**Comment by joosev** [comment]
This does not solve #18. Another PR is for that. ANd the reason why i removed the lines, was a fuck up in my own repository. #18 should have all the changes i removed from this PR.

**Pull request merged**
