### PR TITLE
Fee fix

### PR DESCRIPTION
**Pull request by joosev**

### CODE REVIEW

**Comment by joosev** [comment]
Hups.. accidentally doing pull request with also fix to custom prices per shipping provider.

**Comment by joosev** [comment]
So this will fix issue with possibility to define prices with each provider.

**Comment by l3ku** [comment]
Great! Tested this, found a small bug: no matter what price I specify for shipping providers, it is always displayed as 110€ in the frontend (images below)

WP-Admin
screen shot 2017-12-15 at 11 57 04
WooCommerce checkout screen
screen shot 2017-12-15 at 11 56 53

**Comment by joosev** [comment]
Removed devbugging info.. That will fix that 110. Also added if clause to see, if free tier has value or not.. now everything was bigger value than the free tier

**Comment by ottok** [comment]
Please run `git rebase -i master` in this branch so it gets rebased against latest master, and then force push with `git push origin fee_fix -f`. While doing it, you could also squash some of the commits to the resulting pull request would be clean and easy to review and make sure we together build a top notch quality plugin.

If you are into learning more about git, some tips can be read at https://www.slideshare.net/ottokekalainen/git-best-practices-2016

**Comment by serter** [comment]
@joosev could you review the status of this PR/branch against current seravo master and your own master and perform necessary rebasing and squashing.

If things get too complicated, we could apply the diff manually and commit and push from seravo master.

**Comment by ottok** [comment]
@joosev Do you have plans to rebase this on latest master or should we do it for you? The current state cannot be merged and there are anyway many intermediate commits that should be squashed.

**Comment by joosev** [comment]
I will do the stuff this week

**Comment by ottok** [comment]
Hello! You pushed a 'merge into master' commit. The purpose of pull requests is to merge feature/fix branches (Seravo/woo-commerce or fork) into the master branch of the Seravo/woo-commerce master.

Please please run on your computer:
```
git checkout fee_fix
git rebase -i master
(squash commit, fix merge on master)
git push -f origin fee_fix
```

When the branch fee_fix contains a set of changes that apply on the master branch (but are not yet on the master branch) then it is easy to review and merge.

**Comment by l3ku** [comment]
The contents of this PR were added in 55074aed1541237dc0deaf3ee7c42763a96399a3, closing.

**Pull request closed without merging**
