### PR TITLE
Allow inputting a custom address

### PR DESCRIPTION
**Pull request by k1sul1**
#26 

Works, phpcs is still complaining but I'll fix that as I finish this. I added some placeholder texts but they should probably be changed. 

Any input @joosev?

### CODE REVIEW

**Comment by joosev** [comment]
Screenshot would be nice

**Comment by k1sul1** [comment]
with custom address

image

without custom address
image

**Comment by joosev** [comment]
- No finnish translations in the PR.
- Defacto standard for pickup point search is text-field, not textarea. Maybe it could even be search type? (not sure if it would apply to this case that well).
- Display a warning text or something if no pickup points can be found using the search and then don't remove pickup points that are visible.

**Comment by k1sul1** [comment]
> No finnish translations in the PR.

As I said, the text could use some work. Not going to translate anything before the text is finalized. 

> Defacto standard for pickup point search is text-field, not textarea. Maybe it could even be search type? (not sure if it would apply to this case that well).

Search input is definitely not the one here. It was a text field until I realised that it looks terrible on Storefront, and thus probably every other theme. You can fit like 15 characters in the input before it starts clipping out. Making it a text field is literally removing `area` from `textarea`, so it's a non issue really. I'd use the textarea because it allows fitting the entire query on the input, but if you want a text input, text input you shall have. 

> Display a warning text or something if no pickup points can be found using the search and then don't remove pickup points that are visible.

Does the current implementation show warning text if it's not able to find any pickup points? I can't recall and I closed my work computer already, but I might be able to just use that if it does. 

What do you mean by "don't remove pickup points that are visible"? My guess is that it means showing the pickup points available for the "original" address, but what is the point of that? Why not just prevent user from continuing checkout until they provide an address that works, instead of creating confusing UI. Especially if we're already going to go through the effort of showing a warning message for no pickup points :)

**Comment by joosev** [comment]
Ok, let's go with the textarea for now.

**Comment by joosev** [comment]
There are two ways to handle "no pickup points found". Eather:
1) show warning and no pickup points
2) show warning and show default pickup poitns.

if 1 is done now, let's go with it.

**Comment by k1sul1** [comment]
image

image

image

**Comment by k1sul1** [comment]
@joosev is this ok?

I'll squash-merge and tag 2.2 if it is.

**Comment by ottok** [comment]
Good that you documented the wp-cli 2.3 requirement! That [bug in wp-cli was fixed](https://github.com/wp-cli/i18n-command/pull/173) by the previous maintainer of this plugin :)

Please check your `git config user.email` and `user.name`. Now commits are made as `Christian <me@kisu.li>`.

I'd recommend to not make any changelog or version bumps in pull requests. Rather bump the version number and make a release directly on master as a separate step and at a time when we are sure we want to make a release and can update the changelog to include all changes from this PR and all previous or parallel changes.

**Comment by joosev** [comment]
I think proper finnish translation would be: "Hae vaihtoehtoista noutopistettä"

And also the tip text there should be: "Voit myös hakea noutopisteitä syöttämällä vaihtoehtoisen osoitteen ylläolevaan kenttään."

Also, there might be cases where merchants don't want to allow custom pickup point searches, so let's put an option to settings to allow disable that feature. By default, make it "on".

**Comment by k1sul1** [comment]
> Please check your git config user.email and user.name. Now commits are made as Christian <me@kisu.li>

Oops. I'll fix that, accidentally used my global gitconfig after migrating to a new machine. 

> I'd recommend to not make any changelog or version bumps in pull requests. Rather bump the version number and make a release directly on master as a separate step and at a time when we are sure we want to make a release and can update the changelog to include all changes from this PR and all previous or parallel changes.

Ok, I will keep that in mind in the future. Do you want me to revert the changelog commit?

I'll do the changes requested by @joosev tomorrow

**Comment by k1sul1** [comment]
It's done. 

image

**Pull request merged**
