### PR TITLE
Update repository settings for Github.com/Pakettikauppa account

### PR DESCRIPTION
**Pull request by ottok**
Use unmodified action-wordpress-plugin-asset-update from upstream 10up

### CODE REVIEW

**Comment by ottok** [comment]
@joosev Refreshed PR and now Travis-CI triggered correctly. Merging in this would also fix the Github Actions settings.

**Comment by ottok** [comment]
Unfortunately tests failed on PHP 7.1 / WP 4.9.x are emitting:
```
PHP Fatal error:  Uncaught Error: Call to undefined function determine_locale() in /tmp/wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php:605
Stack trace:
#0 /tmp/wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(573): WooCommerce->load_plugin_textdomain()
#1 /tmp/wordpress/wp-includes/class-wp-hook.php(286): WooCommerce->init('')
#2 /tmp/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /tmp/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /tmp/wordpress/wp-settings.php(450): do_action('init')
#5 /tmp/wordpress-tests-lib/includes/bootstrap.php(105): require_once('/tmp/wordpress/...')
#6 /home/travis/build/Pakettikauppa/woo-pakettikauppa/tests/bootstrap.php(37): require('/tmp/wordpress-...')
#7 phar:///tmp/phpunit/phpunit/Util/Fileloader.php(52): include_once('/home/travis/bu...')
#8 phar:///tmp/phpunit/phpunit/Util/Fileloader.php(36): PHPUnit_Util_Fileloader::load('/home/travis/bu...')
#9 phar:///tmp/phpunit/phpunit/TextUI/Comman in /tmp/wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 605
Fatal error: Uncaught Error: Call to undefined function determine_locale() in /tmp/wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 605
Error: Call to undefined function determine_locale() in /tmp/wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 605
```
https://travis-ci.com/github/Pakettikauppa/woo-pakettikauppa/jobs/464461940

**Comment by joosev** [comment]
I think determine_locale() function was added in wp5.0

**Comment by joosev** [comment]
Because wp 5.0 was released 2 years ago, I think we can make our plugin minimun requirement wp 5.0.0

**Review by joosev — APPROVED** [review]

**Pull request merged**
