### PR TITLE
Add a setup wizard to guide the user through the settings

### PR DESCRIPTION
**Pull request by l3ku**
Screenshots:
### Admin notice that can be used to access the wizard when the install is new
Screen Shot 2019-09-06 at 14 42 00
### Setup wizard setps
Screen Shot 2019-09-06 at 14 54 13
Screen Shot 2019-09-06 at 14 54 56
Screen Shot 2019-09-06 at 14 55 12
Screen Shot 2019-09-06 at 14 55 23
Screen Shot 2019-09-06 at 14 55 33

### CODE REVIEW

**Comment by ottok** [comment]
@l3ku Please rebase on master

@joosev Any comments here, shall we merge this now?

**Comment by joosev** [comment]
don't show:
- Postiennakko stuff
- "Näytä noutopisteet"
- don't show options "tulosta pakettikortit" or "LÄhetä urliin"
- Noutopistehaun rajoitus
- lähetyksien info koodi
- "ja postiennakon osoitetiedoissa"

By default select attach tracking code to email

prefill sender information from store settings

on front page add link to www.pakettikauppa.fi for registering to pakettikauppa (open in new window).

**Comment by l3ku** [comment]
- Rebased on master
- Removed requested settings from the setup wizard
- Removed text "ja postiennakon osoitetiedoissa"
- Added default option values for sender info & "attach tracking code to email" option to WC_Pakettikauppa_Shipping_Method
- Added a link to the setup wizard front page that advises to register to www.pakettikauppa.fi

**Comment by ottok** [comment]
Is this OK to @joosev now?

**Comment by joosev** [comment]
Regarding to see if it's a new install or not:

class-wc-pakettikauppa-shipment.php has a function called get_settings(); and that class is loaded admin->load();

Should the count(*) where settings like 'woo_pakettikauppa_%' be replaces by using that get_settings() and see if it's empty?

This is a suggestion/question.

**Comment by l3ku** [comment]
> Regarding to see if it's a new install or not:
> 
> class-wc-pakettikauppa-shipment.php has a function called get_settings(); and that class is loaded admin->load();
> 
> Should the count(*) where settings like 'woo_pakettikauppa_%' be replaces by using that get_settings() and see if it's empty?
> 
> This is a suggestion/question.

If it returns the same information, it is of course better to use `get_settings()` instead of `$wpdb` directly. I will look into this soon.

**Comment by l3ku** [comment]
Modified the setup wizard notice triggering mechanism to check wether `WC_Pakettikauppa_Shipment::get_settings()` returns an empty result.

**Comment by ottok** [comment]
This should be all good now, merging.

**Pull request merged**
