### PR TITLE
Lots of fixes

### PR DESCRIPTION
**Pull request by joosev**
This PR includes fixes to many small bugs:
- fixed typos in variable name, missing html elements, wrong css -class
- reformatted code for easier reading
- removed possibility to change shipping method from admin order view
- removed possibility to change pickup point from admin order view
- removed saving shipping label to the filesystem, it is fetched from the Pakettikauppa server when needed => removed creation of the private dir
- added info code support
- filtering shipping methods based on the receivers country
- fixed shipping costs VAT calculation
- trimming inputs for pickup point search

### CODE REVIEW

**Comment by ottok** [comment]
Thanks for the pull request!

CI for WordPress multisite failed at: https://travis-ci.org/Seravo/woo-pakettikauppa/builds/446041140

I restarted the build to check if the failure is repeatable.

**Comment by ottok** [comment]
I don't see any Travis-CI integration here: https://github.com/Pakettikauppa/woo-pakettikauppa/commits/pk-master

Note that you can sign up for free at Travis-CI.org and enable it for your repository to get real-time Travis-CI feedback on every single of your own commits during development.

**Comment by ottok** [comment]
Travis-CI is failing due to 
```
Warning: Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to MySQL server on 'localhost' (111)'
Check that mysqld is running on localhost and that the port is 3306.
You can check this by doing 'telnet localhost 3306'
```

This is unrelated to any change in this PR and we will merge the PR despite failing Travis-CI result, and fix the .travis.yml in master afterwards so Travis-CI passes in the future.

**Comment by joosev** [comment]
Due to?

**Comment by joosev** [comment]
I think it passed now, but travis just got stuck

**Comment by joosev** [comment]
I can't restart the travis, could you do it?

**Comment by ottok** [comment]
Restarting Travis does not help, see https://github.com/Seravo/woo-pakettikauppa/pull/34#issuecomment-432954054

**Comment by joosev** [comment]
Seems to be that there is something wrong with travis. It doestn' even start the process of testing

**Comment by ottok** [comment]
@joosev What Travis are you talking about? URL? Screenshot?

**Comment by joosev** [comment]
Did not take screenshots and now it seems to work. It just hanged and waited for 10 minutes and failed. Nothing in the log.

**Comment by joosev** [comment]
I even didn't see that mysqladmin error you talked about. Don't know why you see different travis output than I do.

**Pull request merged**
